server:
  port: 8201

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/cloud_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: orderService8201
