
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/cloud_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 120.79.84.68
    port: 6379
    password: 123456789
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8301
