spring:
  application:
    name: zuul-service
  redis:
    host: 120.79.84.68
    port: 6379
    password: 123456789
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8585

zuul:
  ignored-patterns:   # 禁止直接访问该接口,只允许服务调用
    - /**/product/listForOrder
    - /**/product/decreaseStock
  sensitive-headers:  # 接收敏感信息 如 cookie

